dist: trusty
sudo: true
language: python
python:
  - '3.6'
services:
  - xvfb
install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$TRAVIS_BUILD_DIR
  - export PYTHONDONTWRITEBYTECODE=1
script: xvfb-run --server-args="-screen 0 1024x768x24" pytest -v
env:
  global:
    - ANKI_ADDON_ID: 1284759083
    - secure: ZtwnARLqggwl5aoQIPl8gdE3Y8CkRjSFKkdDtjC+hLqKu3YB5+2JfxqjImID1jFSVjOsAGLtWu1GZpAz93V/lQDiiZdAAVeAbTIBOXXB27Vkl9vsZKHXrC5AYCdc0pRxLswduXjUSCbv32N+JSQZe/GIkEdeiqb72LOTFYjlh99RS3jbYEg4YMq5Ovgj20YRY1vLRS6/0/+iZiVrJZE3alo67+zyI0UkUGZ1k6rp5fhqZA5pKfzURets73L71/FPF2aOJB6SaXAbyWQDdi0uRs8uNGsHYtUNzEQ2OHJjrzp6Ai7g97V905be8dxgVYPPGoQdYBLGhaCicCegjlSsmEjzLbYOlyOF7PVtLUiF/gr7OVLijlNr1HBpbfaSnXzbZ9tdWu6hXxPKnD2sLzjadM+nLLg7Sw2GuSGo5rCr8lTq0G3hoOLadyy5TBHkh0d1X23htuD5B1r24X1Jds7uUyHguUlRP//F2Zl0f4D8rul/2SwKQjQb9QS5gl7DE7/mmN2HmPnIdSVq0iD8HqI1POfAw4O9P6jTcFgOnwnGarE/3ylc++vbvMS5qxsJ3vxs0Yli4F7mT444fU/QG2nAG+8Qfxh6CLmDgpsczJptpaP5ve/bGcr8oNvMYMi3KkX31O/KGoY7BmRFSKRSLX1qDqbu6jIdGdO9a4vcAlcmRDo=
    - secure: TxUc+x+HMq7kJKSkpmqciKIW2hf58WHhXStfWvTiScPK+cFGEpYM0rjAPWPM9JLoTcWPsIZIQrfggNLLorFXuALiqrvXw5RJvYIzPv8/sfigdW0OjZqDPLWFun8a34Xa0EGhrqO4Q0UXQodHV+LkDnNozdoofwBkTAAuc4XGxgNga2usDARCnQ8AnxkUJs5Uz+Y605Qk42PzxRh5CLT9QNPyCPa9MMpBl9S9pMmG/4f/1HN7U+aOv908TuWYUx3JwB2j7in/cqXdRvnYHp6RwWth+IC1tXY0maxWXbJ85V9k2sjkRnaDUUwD1KHiDWxtiDsDPtshJyA+S1jMbCETRuueqCTL3JK8rEKx+5FYfrzL7Am/gbJ5Jbg/ESSGiSuf4NOyEkwxM1xTjOnepZd0DN0IQd1ZSWQME+QTPkoBD5i/1hLZz70cpGJLdTIH5NaqW7JcDwhZRVF/q++1JmI1TZxwhbw87vTlTAWODWvHKliETQLer1lONeABvD7x2FVGpG7gFxBBmAeEmPC7mz4XjFJ04YC24LDSP5aEZJVke8LdiyNN4tMsEVyncessh0njYNFfzXlexxdHp7VUkCAbSQyM6Sj65+ELZFvLUvFSOuRtcMfZFgQik6yl7ypbkO/9wu00PUa8T3vZlpOCmieJgfsGHSw8SYuE+zpiv5J8tcM=

deploy:
  - provider: script
    script: python deploy.py
    on:
      branch: master

  - provider: releases
    api-key:
      secure: dRGQfrEcQJyhKjk7LNv4HHFvUPQWsHDuaAp1oqs0LuxjSz0Mb3LcbMJzEdqqNcnL1DN777Vm82Fwy5zxI23xPVgUdmwlkxualV/gC6mzIBlUHk5CHzV1Rx2uczWWyglRiGKHyOoL6JDIk7FULuPyKUT75uTC5GRS3K1q7u07lsXu8pr9P7+Esv0YuR59cQtMEZ93aiIXnRFoFMqZ5h2hHaifd6GYfn6ojOqJKXOTRbC8sCOx6ZGTB34ZJ9jNPD7fnQjpsh+WyErrW8f9TXwN2eDLUDFpgy54gPx15GzmmbTFZ+zX1YtpPQbtS0YAIAWJZl0WuZ9o2XNUgpVZfWJ7Gy/vLbFn7ZBQZs+vVpp8OiDAgwaq2GciQZhBs/noXe8whRT2v753j0YoaMLcx59viJHfRdMTgGnqeavS5lxzSM5g1oSenRfatDg2bs/FGX1UVpjeY6wOrTt46W6O79nP3YTZmWmRO25TEbPJ3SH8uDj3ofLOcnUngnEeCTfiLED8CIDEY0B/WUyb8KJ5EGrZQHhodGse/YCXNafkviiVNsoNqWgWhWtGhW/AuIeiGUw2KlwQppigyK/162tzYWy5+xvOLqQXPiFbZWMJSHDaxusvoIE5J8CK8tKzXNa3+QCoYnLyQSF2B/P9KepuBzn47VBL25NJAwoMedKprCt1SbY=
    file_glob: true
    file: Dict2Anki-*.zip
    skip_cleanup: false
    draft: true
    on:
      branch: master